module: cnn.feature_extraction.FeatureExtraction
model: cnn.TwoHeadResNet50Model
dataset: cholec80_feature_extract.Cholec80FeatureExtract

data_root: D:/VC/toy/processed
out_features: 7

input_height: 224
input_width: 224

batch_size: 8
fps_sampling: 5
fps_sampling_test: 5

learning_rate: 0.0005
dataset_mode: img_multilabel
early_stopping_metric: val_acc_phase
pretrained: True
save_top_k: 1

max_epochs: 2
min_epochs: 1
num_tasks: 1
num_sanity_val_steps: 0
test_extract: True
num_workers: 2
gpus: 1